valayDave/tell-me-your-secrets

.github/workflows/ci.yml, requirements-test.txt, tell_me_your_secrets/__main__.py, tell_me_your_secrets/utils.py, test/test_regex_signature.py, test/test_simple_match.py
Laying the way for the foundations of setting up some automation. I am not sure how best to do this on a forked repo but verified it on my fork.
See: https://github.com/inverse/tell-me-your-secrets/pull/1/checks?check_run_id=861563069
In this PR
- Add foundations for CI that runs a very basic test suite on PR
- Minor style changes (we could check this by using a linter but didnt wanna go overboard)
p.s. do you squash when you merge? It makes history look cleaner - you can set this as the default in the settings.
=> Foundations for CI

setup.py
- Bump version as requested
- Tidy setup.py (I can extend the CI to cover cases)
=> Bump version + tidy setup.py

.github/workflows/publish.yml
Resolves #7 
- Triggers on tag ( need to test the rule) documentation is here: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-branches-and-tags
~~The only part that would be great to figure out is how to trigger the normal ci pipeline so that it runs the full linting/testing before publish.~~ This isn't a blocker since the CI pipeline will have kicked in for any push/merge to master but will assume that it's run and succeeded.
=> Scaffold out pypy publish

LICENSE.txt, Readme.md
- Add badges
- Tidy + typo fix
- Bump year on licence
=> Readme improvements

.github/workflows/ci.yml
Extends the CI suit to run tests in matrix covering Python versions:
- 3.6
- 3.7
- 3.8
I had to drop 3.4 and 3.5 as they were completely broken.
See: https://github.com/valayDave/tell-me-your-secrets/actions/runs/261727350
N/A
-   [x] Tests have been added to verify that the new code works (if possible)
=> Run tests in matrix

.gitignore, setup.py, tell_me_your_secrets/__init__.py
- Prepare for new release (`2.0.0`)  
- Load version from `__init__.py`
- Wrap all utils in `setup.py` into functions for encapsulation
Resolves #26 
Run `python setup.py sdist bdist_wheel`
_Assuming you have `wheel` installed in your venv_
=> Prep for new release

.github/workflows/publish.yml
Change publish trigger to be when Github release created
See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
N/A
=> Update publish trigger

.github/workflows/ci.yml, setup.py
Python 3.9 got released recently - lets see how well it performs under tests
See: https://docs.python.org/3.9/whatsnew/3.9.html
N//A
-   [x] Tests have been added to verify that the new code works (if possible)
=> Add python 3.9 to matrix test

README.md, tell_me_your_secrets/__main__.py, tell_me_your_secrets/config.yml, test/test_regex_signature.py, test/test_simple_match.py
Add the ability to explicitly whitelist strings.
- Create a test directory with a file which has something that would normally match one of the rules.
- Ignore that within the config in `whitelisted_strings` 
- Run the module :)
-   [x] Tests have been added to verify that the new code works (if possible)
-   [x] Documentation has been updated to reflect changes
=> Add whitelisted string functionality

.github/pull_request_template.md, CHANGELOG.md
Add changelog to capture changes - will make it easier to draft releases + easily skim through whats changed between versions.
N/A
=> Add changelog + update template

CHANGELOG.md, tell_me_your_secrets/processor.py, tell_me_your_secrets/utils.py, test/test_processor.py
- Return all matches not just first
- Use class to represent match
- Resolves #36 
Scan a directory with a file containing more than one mach and it'll show up.
=> Return all matches not just first

README.md
=> Add download stats

CHANGELOG.md, README.md, tell_me_your_secrets/__main__.py
- Add `--version` flag to print version. Resolves #42 
- Tidy argparse
- Add pipx install method
```bash
python -m tell_me_your_secrets --version
```
-   [x] Documentation has been updated to reflect changes
=> Add version flag

CHANGELOG.md, tell_me_your_secrets/__main__.py, tell_me_your_secrets/utils.py, test/test_load_signatures.py
Fix 3 of the codacy warnings on unsafe YAML loading.
=> Use yaml safe loader

README.md
=> Add Codacy coverage badge

CHANGELOG.md, tell_me_your_secrets/config.yml
Add support for more Slack token formats
=> Add support for more Slack token formats

CHANGELOG.md, setup.py, tell_me_your_secrets/utils.py
- Tidy setup.py
- Resolve version better
- Remove invalid classifiers
- Return rules as a unique list since some rules are duplicated
=> Tidy setup + signature output

CHANGELOG.md
=> Fix changelog PR ref

.pre-commit-config.yaml
Bump pre-commit framework
```bash
pre-commit run -a
```
It also runs on CI
=> Bump pre-commit framework

CHANGELOG.md, requirements-test.txt, setup.py, tell_me_your_secrets/__main__.py
Resolves #16 by correctly setting exit code packaged code
Using pipx run `pipx install .` within the source doe and then run `tell-me-your-secrets -e . ; echo $?` from a folder without any issues.
=> Fix exit code on entrypoint

.github/dependabot.yml
Add GitHub actions to dependabot update check
=> Add github-actions dependabot
